---
abstract: 'Perl extension for base 85 numbers, as referenced by RFC 1924'
author:
  - 'Tony Monroe <tmonroe plus perl at nog dot net>'
  - 'Paul Cochrane <ptc@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-Base85
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '0'
  Math::BigInt: '0'
  constant: '0'
  perl: '5.006'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/paultcochrane/Math-Base85/issues
  repository: https://github.com/paultcochrane/Math-Base85
version: '0.5'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
